export const decorationUncoveredCodeRegionHoverMessage = "This code region is not covered by a test known by cmake." as const;
export const errorWorkspaceNotLoaded = "A workspace must be loaded to get coverage information." as const;
export const progressComputingRegionsLocations = "Computing uncovered code region locations" as const;
export const progressCoverageInfoReady = "Prepared summary and uncovered region of code information." as const;
export const progressFoundCMake = "Found an invocable cmake command." as const;
export const progressGeneratedCmakeProject = "Generated the cmake project." as const;
export const progressResolvedBuildTreeDirectory = "Resolved build tree directory path." as const;
export const progressResolvedLLVMFile = "Resolved the LLVM coverage information file path." as const;
export const progressTargetBuilt = "Built the target." as const;